[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chickenpi"
version = "1.0.0"
description = "Backend for automating chicken coop with raspberry pi."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "firebase-admin>=7.5.0",
    "gpiozero>=2.0.1",
    "opencv-python-headless>=5.0.0.93",
    "python-json-logger>=4.2.0",
    "rpi-lgpio>=0.6",
    "sentry-sdk[fastapi]>=2.68.1",
    "uvicorn[standard]>=0.52.4",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
addopts = "--capture sys"
testpaths = [
    "tests",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["chickenpi*"]
