[project]
name = "chickenpi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gpiozero>=2.0.1",
    "rich>=14.0.0",
    "rpi-gpio>=0.7.1",
]
