[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chickenpi"
version = "1.0.0"
description = "Backend for automating chicken coop with raspberry pi."
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi[standard]==0.141.1",
    "firebase-admin==7.5.0",
    "gpiozero==2.0.1",
    "opencv-python-headless==5.0.0.93",
    "python-json-logger==4.2.0",
    "rpi-lgpio==0.6",
    "sentry-sdk[fastapi]==2.68.1",
    "uvicorn[standard]==0.52.4",
    "numpy==2.4.6",
    "httptools==0.8.0",
    "pyyaml==6.0.3",
]

[global]
extra-index-url = ["https://www.piwheels.org/simple"]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
addopts = "--capture sys"
testpaths = [
    "tests",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["chickenpi*"]

[tool.uv.sources]
opencv-python-headless = { url = "https://piwheels.org/simple/opencv-python-headless/opencv_python_headless-5.0.0.93-cp311-cp311-linux_armv7l.whl" }
numpy = { url = "https://piwheels.org/simple/numpy/numpy-2.4.6-cp311-cp311-linux_armv7l.whl" }
httptools= { url = "https://piwheels.org/simple/httptools/httptools-0.8.0-cp311-cp311-linux_armv7l.whl" }
pyyaml= { url = "https://piwheels.org/simple/pyyaml/pyyaml-6.0.3-cp311-cp311-linux_armv7l.whl" }

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'armv7l'"
]

[[tool.uv.index]]
name = "piwheels"
url = "https://www.piwheels.org/simple"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true