name: Deploy to Raspberry Pi

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install uv

      - name: Build artifact with uv
        run: |
          . .venv/bin/activate
          uv build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: dist/*.*-py3-none-any.whl

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_KEY }}
          script: |
            echo "get latest release"
