# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: frontend/chickenpi
    - name: build frontend
      run: npm run build #--if-present
      working-directory: frontend/chickenpi
    #- run: npm test

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: astral-sh/setup-uv
      uses: astral-sh/setup-uv@v6.4.3
      with:
        cache-dependency-glob: "**/uv.lock"
    - name: build backend
      run: uv pip install .

  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
          
